// Autogenerated items filter functionality
document.addEventListener('DOMContentLoaded', function() {
    const filterCheckbox = document.getElementById('show-autogenerated');
    const itemsContainer = document.getElementById('items-container');
    
    if (!filterCheckbox || !itemsContainer) return;
    
    // Function to update item visibility
    function updateItemVisibility() {
        const showAutogenerated = filterCheckbox.checked;
        const autogeneratedItems = itemsContainer.querySelectorAll('.autogenerated-item');
        
        autogeneratedItems.forEach(item => {
            if (showAutogenerated) {
                item.classList.remove('hidden');
            } else {
                item.classList.add('hidden');
            }
        });
        
        // Update results count
        updateResultsCount();
    }
    
    // Function to update the results count
    function updateResultsCount() {
        const resultsCount = document.querySelector('.results-count');
        if (!resultsCount) return;
        
        const allItems = itemsContainer.querySelectorAll('.item-card');
        const visibleItems = itemsContainer.querySelectorAll('.item-card:not(.hidden)');
        
        const totalCount = allItems.length;
        const visibleCount = visibleItems.length;
        
        resultsCount.textContent = `Showing ${visibleCount} of ${totalCount} items`;
    }
    
    // Save filter state to localStorage
    function saveFilterState() {
        localStorage.setItem('showAutogenerated', filterCheckbox.checked);
    }
    
    // Load filter state from localStorage
    function loadFilterState() {
        const savedState = localStorage.getItem('showAutogenerated');
        if (savedState !== null) {
            filterCheckbox.checked = savedState === 'true';
            updateItemVisibility();
        }
    }
    
    // Event listener for checkbox change
    filterCheckbox.addEventListener('change', function() {
        updateItemVisibility();
        saveFilterState();
    });
    
    // Load saved state on page load
    loadFilterState();
    
    // Also work with table view if it exists
    const tableContainer = document.querySelector('.items-table');
    if (tableContainer) {
        const tableFilterCheckbox = document.querySelector('#show-autogenerated-table');
        if (tableFilterCheckbox) {
            tableFilterCheckbox.addEventListener('change', function() {
                const showAutogenerated = tableFilterCheckbox.checked;
                const rows = tableContainer.querySelectorAll('tr[data-autogenerated="true"]');
                
                rows.forEach(row => {
                    row.style.display = showAutogenerated ? '' : 'none';
                });
                
                localStorage.setItem('showAutogenerated', tableFilterCheckbox.checked);
            });
            
            // Sync with main checkbox
            const savedState = localStorage.getItem('showAutogenerated');
            if (savedState !== null) {
                tableFilterCheckbox.checked = savedState === 'true';
                tableFilterCheckbox.dispatchEvent(new Event('change'));
            }
        }
    }
});