// Endless scrolling functionality
(function() {
    'use strict';
    
    // Configuration
    const ITEMS_PER_LOAD = 50;
    const SCROLL_THRESHOLD = 1000; // pixels from bottom to trigger load
    
    // State
    let currentPage = 1;
    let isLoading = false;
    let hasMoreItems = true;
    let allItems = [];
    let displayedItems = 0;
    let showAutogenerated = true;
    
    // DOM elements
    let itemsContainer;
    let loadingIndicator;
    let noMoreItemsMessage;
    let resultsCount;
    let autogeneratedCheckbox;
    
    // Initialize
    document.addEventListener('DOMContentLoaded', function() {
        console.log('Endless scroll: DOMContentLoaded');
        itemsContainer = document.getElementById('items-container');
        if (!itemsContainer) {
            console.log('Endless scroll: No items container found, exiting');
            return; // Exit if not on a page with items
        }
        console.log('Endless scroll: Items container found');
        
        // Get autogenerated checkbox
        autogeneratedCheckbox = document.getElementById('show-autogenerated');
        if (autogeneratedCheckbox) {
            showAutogenerated = autogeneratedCheckbox.checked;
            autogeneratedCheckbox.addEventListener('change', handleAutogeneratedFilter);
        }
        
        // Check if we have pagination links (indicates multiple pages)
        const paginationElement = document.querySelector('.pagination');
        console.log('Endless scroll: Pagination element found?', !!paginationElement);
        
        if (paginationElement) {
            // Find all pagination links to determine total pages
            const paginationLinks = paginationElement.querySelectorAll('.pagination-link');
            console.log('Endless scroll: Found pagination links:', paginationLinks.length);
            let totalPages = 1;
            
            // Find the highest page number
            paginationLinks.forEach(link => {
                const pageNum = parseInt(link.textContent);
                if (!isNaN(pageNum) && pageNum > totalPages) {
                    totalPages = pageNum;
                }
            });
            
            console.log('Endless scroll: Total pages detected:', totalPages);
            
            // Only set up endless scroll if there are multiple pages
            if (totalPages > 1) {
                // Store all current items
                const currentItems = itemsContainer.querySelectorAll('.item-card');
                allItems = Array.from(currentItems);
                displayedItems = allItems.length;
                
                // Hide pagination
                paginationElement.style.display = 'none';
                
                // Add loading indicator
                createLoadingIndicator();
                
                // Add "Load More" button option
                createLoadMoreButton();
                
                // Set up scroll listener for endless scrolling
                setupScrollListener();
                
                hasMoreItems = currentPage < totalPages;
                
                console.log('Endless scroll initialized. Total pages:', totalPages);
            }
        }
        
        // Update results count
        resultsCount = document.querySelector('.results-count');
        updateResultsCount();
    });
    
    function createLoadingIndicator() {
        loadingIndicator = document.createElement('div');
        loadingIndicator.className = 'loading-indicator';
        loadingIndicator.innerHTML = `
            <div class="loading-spinner"></div>
            <p>Loading more items...</p>
        `;
        itemsContainer.parentNode.insertBefore(loadingIndicator, itemsContainer.nextSibling);
    }
    
    function createLoadMoreButton() {
        console.log('Creating load more button');
        const loadMoreButton = document.createElement('button');
        loadMoreButton.className = 'load-more-button';
        loadMoreButton.textContent = 'Load More Items';
        loadMoreButton.addEventListener('click', function() {
            console.log('Load more button clicked');
            loadMoreItems();
        });
        
        itemsContainer.parentNode.insertBefore(loadMoreButton, loadingIndicator);
        console.log('Load more button added to DOM');
    }
    
    function createNoMoreItemsMessage() {
        noMoreItemsMessage = document.createElement('div');
        noMoreItemsMessage.className = 'no-more-items';
        noMoreItemsMessage.textContent = 'No more items to load';
        noMoreItemsMessage.style.display = 'none';
        itemsContainer.parentNode.insertBefore(noMoreItemsMessage, loadingIndicator.nextSibling);
    }
    
    function setupScrollListener() {
        let scrollTimer;
        
        window.addEventListener('scroll', function() {
            clearTimeout(scrollTimer);
            scrollTimer = setTimeout(function() {
                if (shouldLoadMore()) {
                    loadMoreItems();
                }
            }, 100);
        });
    }
    
    function shouldLoadMore() {
        if (isLoading || !hasMoreItems) return false;
        
        const scrollPosition = window.scrollY + window.innerHeight;
        const documentHeight = document.documentElement.scrollHeight;
        
        return (documentHeight - scrollPosition) < SCROLL_THRESHOLD;
    }
    
    function loadMoreItems() {
        console.log('Load more items called. isLoading:', isLoading, 'hasMoreItems:', hasMoreItems);
        if (isLoading || !hasMoreItems) return;
        
        isLoading = true;
        currentPage++;
        console.log('Loading page:', currentPage);
        
        // Show loading indicator
        if (loadingIndicator) {
            loadingIndicator.classList.add('active');
        }
        
        // Hide load more button while loading
        const loadMoreButton = document.querySelector('.load-more-button');
        if (loadMoreButton) {
            loadMoreButton.disabled = true;
        }
        
        // Construct the URL for the next page
        const currentPath = window.location.pathname;
        let nextPageUrl;
        
        // Extract base path and relative path
        const pathParts = currentPath.split('/');
        const fileName = pathParts[pathParts.length - 1];
        const basePath = currentPath.substring(0, currentPath.lastIndexOf('/') + 1);
        
        if (fileName.includes('-page-')) {
            // Already on a paginated page
            nextPageUrl = basePath + fileName.replace(/-page-\d+\.html/, `-page-${currentPage}.html`);
        } else if (fileName.includes('products.html')) {
            // On main products page
            nextPageUrl = basePath + fileName.replace('products.html', `products-page-${currentPage}.html`);
        } else if (fileName.includes('.html')) {
            // Category or manufacturer page
            nextPageUrl = basePath + fileName.replace('.html', `-page-${currentPage}.html`);
        } else {
            nextPageUrl = currentPath + `page-${currentPage}.html`;
        }
        
        console.log('Loading page:', currentPage, 'URL:', nextPageUrl);
        
        // Fetch the next page
        fetch(nextPageUrl)
            .then(response => {
                if (!response.ok) {
                    throw new Error('No more pages');
                }
                return response.text();
            })
            .then(html => {
                // Parse the HTML
                const parser = new DOMParser();
                const doc = parser.parseFromString(html, 'text/html');
                
                // Extract items
                const newItems = doc.querySelectorAll('.item-card');
                
                if (newItems.length > 0) {
                    // Add new items to the container
                    newItems.forEach(item => {
                        const clonedItem = item.cloneNode(true);
                        
                        // Apply autogenerated filter if needed
                        if (!showAutogenerated && clonedItem.classList.contains('autogenerated-item')) {
                            clonedItem.classList.add('hidden');
                        }
                        
                        itemsContainer.appendChild(clonedItem);
                        allItems.push(clonedItem);
                    });
                    
                    displayedItems += newItems.length;
                    updateResultsCount();
                    
                    // Check if there are more pages
                    const nextPagination = doc.querySelector('.pagination');
                    if (nextPagination) {
                        // Look for next page link
                        const nextPageLinks = nextPagination.querySelectorAll('a[href*="-page-"]');
                        let hasNext = false;
                        nextPageLinks.forEach(link => {
                            const href = link.getAttribute('href');
                            const pageMatch = href.match(/-page-(\d+)\.html/);
                            if (pageMatch && parseInt(pageMatch[1]) === currentPage + 1) {
                                hasNext = true;
                            }
                        });
                        hasMoreItems = hasNext;
                    } else {
                        hasMoreItems = false;
                    }
                } else {
                    hasMoreItems = false;
                }
                
                if (!hasMoreItems) {
                    showNoMoreItems();
                }
            })
            .catch(error => {
                console.log('No more items to load');
                hasMoreItems = false;
                showNoMoreItems();
            })
            .finally(() => {
                isLoading = false;
                
                // Hide loading indicator
                if (loadingIndicator) {
                    loadingIndicator.classList.remove('active');
                }
                
                // Re-enable load more button
                const loadMoreButton = document.querySelector('.load-more-button');
                if (loadMoreButton) {
                    loadMoreButton.disabled = false;
                    if (!hasMoreItems) {
                        loadMoreButton.style.display = 'none';
                    }
                }
            });
    }
    
    function showNoMoreItems() {
        if (!noMoreItemsMessage) {
            createNoMoreItemsMessage();
        }
        if (noMoreItemsMessage) {
            noMoreItemsMessage.style.display = 'block';
        }
        
        // Hide load more button
        const loadMoreButton = document.querySelector('.load-more-button');
        if (loadMoreButton) {
            loadMoreButton.style.display = 'none';
        }
    }
    
    function handleAutogeneratedFilter() {
        showAutogenerated = autogeneratedCheckbox.checked;
        
        // Apply filter to all items
        allItems.forEach(item => {
            if (item.classList.contains('autogenerated-item')) {
                if (showAutogenerated) {
                    item.classList.remove('hidden');
                } else {
                    item.classList.add('hidden');
                }
            }
        });
        
        updateResultsCount();
    }
    
    function updateResultsCount() {
        if (!resultsCount) return;
        
        const visibleItems = allItems.filter(item => !item.classList.contains('hidden')).length;
        const totalText = resultsCount.textContent.match(/of (\d+)/);
        const totalItems = totalText ? totalText[1] : displayedItems;
        
        resultsCount.textContent = `Showing ${visibleItems} of ${totalItems} items`;
    }
})();